### ISSUE TITLE
building chipmunk

### ISSUE THREAD

**Issue by elekesabel** [viblo/pymunk#102]
Hi!
I want to install pymunk 4.0.0 (5.0.0 is not good for me unfortunatelly) . I'm using python 3.5, Win10 64bit.
When I "python setup.py install" it installs, but then when I'm trying to use it it says the generic 

```
`Failed to load pymunk library.

This error usually means that you don't have a compiled version of chipmunk in
the correct spot where pymunk can find it. pymunk does not include precompiled
chipmunk library files for all platforms.
The good news is that it is usually enough (at least on *nix and OS X) to
simply run the compile command first before installing and then retry again:

You compile chipmunk with
> python setup.py build_chipmunk
and then continue as usual with
> python setup.py install
> cd examples
> python basic_test.py
...`
```

so I uninstalled and tried to build chipmunk, but then this happens:

```
`running build_chipmunk

compiling chipmunk in Debug mode (Defualt, prints debug output and asserts)

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe -std=gnu99 -ffast-math -DCHIPMUNK_FFI -Wno-unknown-pragmas -fPIC -DCP_USE_CGPOINTS=0 -mrtd -O3 -shared -fno-omit-frame-pointer -m64 /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ichipmunk_src\include\chipmunk "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcchipmunk_src\chipmunk.c /Fochipmunk_src\chipmunk.obj

cl : Command line error D8021 : invalid numeric argument '/Wno-unknown-pragmas'

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2`
```

I don't know what to do, I'm quite new in this stuff. I usually just pip install everything. (Also with pip install pymunk=4.0.0" it didnt work)

Thanks for the help.

**Comment by viblo** [comment]
Are you using 64bit or 32bit python?

**Comment by elekesabel** [comment]
Hi!
64bit python sorry.
There is an older project I'd want to follow, an it is written with the v4. When I installed v5 and tried to run, there was an error that pygame_util.py doesnt have 'draw' function.
Thanks for your help!

**Comment by viblo** [comment]
Alright, then I know. 4.0 doesnt support 64bit python on windows, so no precompiled dll is included. Potentially you could try to compile it yourself, but from my experience its quite complicated to make it work (thats why only 5.0 supports it) If you want to do this I suggest you try using mingwpy as your gcc distribution. (https://mingwpy.github.io/) That is what 5.0 uses so might work if you also adjust the compile arguments found in setup.py. 

Otherwise I think it will be easier to just patch the older project to use the updated API. It should be only some small changes required. In 5.0 you need to first create a draw_options object with the drawing surface like this `draw_options = pymunk.pygame_util.DrawOptions(screen)` and then draw the whole space with `space.debug_draw(draw_options)`.

**Comment by elekesabel** [comment]
Thank you for your help! I'll try to update the project, as I'm not really good in compiling these kind of stuff.

**Comment by viblo** [comment]
Ill close this issue. (If you need some help and the other project is open I can take a look and give some tips about what needs to be done to upgrade, just open a new issue if that case.)
