### ISSUE TITLE
point_query_nearest: Sensor shapes are NOT included

### ISSUE THREAD

**Issue by boutboutnico** [viblo/pymunk#113]
Shapes declared as sensor are not found by point_query_nearest.

**Comment by viblo** [comment]
Thanks for the report! Seems to be the same in the segment queries as well.. Anyway, I opened a issue on the chipmunk tracker since this is a bug/"feature" in Chipmunk and pymunk just use whatever chipmunk finds. 

As a workaround you can do a full point_query and take the closest one.

**Comment by viblo** [comment]
I have made it clear in the docs when sensors are included. 
(Im a little bit hesitant to change the behavior until I see some reply from Chipmunk)

**Comment by viblo** [comment]
Closing this issue. 

I got a reply on the Chipmunk issue tracker, but without conclusive result. However, after some thinking recently when looking into API breaking changes, I have decided to label this as a feature/wont fix. 

I can think of two main reasons to keep the current behavior: 
1. To keep consistent with what Chipmunk does. Good for sharing knowledge between languages, and good for easy maintenance of Pymunk (since this change would need to go into the Chipmunk source).
2. In some cases you want sensor shapes when you do the nearest query, sometimes not. So both include and exclude sensors will give  troubles to some use cases, and I think the current behavior is more useful. (In the query functions that return a list of shapes its ok to include them since then you can easily filter out the sensor shapes yourself.)

The best solution would be to add a option to the query I guess, so you could decide yourself. However, I do not feel the effort is worth it since it would be a bit complicated (could reconsider if there was high demand of course).
