### ISSUE TITLE
Pinball continued

### ISSUE THREAD

**Issue by 3kynox** [viblo/pymunk#116]
Hello,

We have to achieve a pinball retro game (Night Mission) for our school and our choices have been set to pygame and pymunk.

However I feel a lot lost with the current docs where we find lot of examples, a sample short tutorial and a API (which is hard to read).

I naturally started to take the pinball example but I'm getting hard to find what I need to continue our project. In the example, we have some great things that explains how to draw static lines (that we can use to place around flat items) and bumpers using elasticity parameter (which is great).

To start with my first problem, I would like for example to be able now to build complex shapes with round borders for the left and right flippers (as the ones provided got strong angles) : 

This -> http://i.imgur.com/vyyZWKn.png
To This -> http://i.imgur.com/6gLUEsE.png

For my learning, how to achieve that result following the pinball example ?

Thanks a lot.

**Comment by viblo** [comment]
For this type of questions I think its better if you write them on [StackOverflow](http://stackoverflow.com/) This issue list is more for bugs, feature requests and such and not so much for general Q/A. Another benefit of SO is that more people will look at your problem and help out.

But since you already wrote here, let me answer: 
First the general case:
What you see on the screen doesnt necessarily have to be exactly the same shape as the actual physics object. Usually the shape used for collision detection (and other physics simulation) is much simplified version of what is drawn on the screen. Even high end AAA games do this.

There are a number of reasons why its good to separate the collision shape and what is drawn.
- Using simpler collision shapes are faster. So if you have a very complicated object, for example a pine tree, maybe it can make sense to simplify its collision shape to a triangle for performance.
- Using a simpler collision shape make the simulation better. Lets say you have a floor made of stone with a small crack in the middle. If you drag a box over this floor it will get stuck on the crack. But if you simplify the floor to just a plane you avoid having to worry about stuff getting stuck in the crack.
- Making the collision shape smaller (or bigger) than the actual object makes gameplay better. Lets say you have a player controlled ship in a shoot-em-up type game. Many times it will feel more fun to play if you make the collision shape a little bit smaller compared to what it should be based on how it looks.

For your particular case:
You can draw the rounded border flipper on top of the physics shape. Then its only a matter of what physics shape is good enough. For this case maybe the triangle used in the example is not good enough, so instead you need to make a more complicated Poly shape. Since you create a Poly by specifying the vertices you can make the shape as close to the rounded flipper picture as you want.
Another option is to combine a Poly in a rectangle shape and then add a Circle on the "end" of the flipper to make it rounded. 
Finally maybe it can be made rounded by using the radius parameter when creating the triangle shape used in the example.

**Comment by 3kynox** [comment]
Thanks for your answer and some details, I will ask on stackexchange for next questions.
I still get difficulties to build a shape with poly pymunk element. Is there some examples around to help me define more complex poly ?

I defined already lot of static lines for the pinball physic areas and bumpers like on the example.

I understand the two options you explained that make sense of how to achieve the flippers but an example of how to define a shape with poly element is the bridge missing for me to accomplish this. I tried already to take a quick look on various examples bundled with the project but did not found what I was needing.

Another challenge I have to do also is place the ball near the launcher (this is simple to do) but define the launcher, add physics to it, set a force to it, and release it with a specific key. I am actually thinking of how doing this.

Thanks again for all your details.

**Comment by viblo** [comment]
So a Poly shape is defined by the vertices (x,y) pairs. So in your code snipped you have defined these as (5,-5), (-85,0) and (5,5). If you want a more complex shape I suggest you build on that list. For example, to make the "pointy" part less pointy you can add another point in the middle, like this `fp = [(5,-5), (-85, -2), (-85,2), (5,5)]`

If you have a specific shape in mind I suggest you draw it on paper first (easiest with graph paper) and in that way find out the coordinates you need.

I think a launcher is easiest to make very basic to start with. Make a two straight segment shapes as walls, another one as the floor then place the ball in between. Finally use the Body.apply_impulse_at_local_point function to give it some speed upwards (http://www.pymunk.org/en/latest/pymunk.html#pymunk.Body.apply_impulse_at_local_point). No need to actually make the launcher mechanism to start with. (You can track for how long the player is pressing the launch key and adjust the impulse size if you to make it more realistic, arrows.py example contains an example on similar functionality)
