### ISSUE TITLE
Collision handling sensitive to order in which objects are added

### ISSUE THREAD

**Issue by Rick-C-137** [viblo/pymunk#119]
I'm building simple block towers with rectangular blocks. The top y-coordinate of one block is exactly equal to the bottom y-coordinate of the one above it (e.g. the top of block 1 is y=50 and the bottom of block 2 resting on top of it is also y=50). I discovered that if blocks are added to the space in a different order, say block 1 then 2 then 3 then 4, ..., versus 2, 1, 5, 3, ..., the collisions resolutions are handled differently at the outset, causing divergent simulations. Is there some reason for this that you can think of? Is it generally not good practice to make the shapes exactly touch, like I have?

**Comment by viblo** [comment]
Im on vacation without computer now so I can't give a full reply. But in
general Im not surprised, different order of objects could generate
different collision response.

It also feels reasonable to add objects already touching exactly on top of
each other. Note that the way pymunk works objects always sink into each
other a little bit, so even if you add them exactly on top each other they
might sink into each other when simulation is started.

On Jul 21, 2017 22:25, "Chris Bates" <notifications@github.com> wrote:

I'm building simple block towers with rectangular blocks. The top
y-coordinate of one block is exactly equal to the bottom y-coordinate of
the one above it (e.g. the top of block 1 is y=50 and the bottom of block 2
resting on top of it is also y=50). I discovered that if blocks are added
to the space in a different order, say block 1 then 2 then 3 then 4, ...,
versus 2, 1, 5, 3, ..., the collisions resolutions are handled differently
at the outset, causing divergent simulations. Is there some reason for this
that you can think of? Is it generally not good practice to make the shapes
exactly touch, like I have?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/viblo/pymunk/issues/119>, or mute the thread

**Comment by viblo** [comment]
I just want to add that I made a small test myself and also got the behavior you describe. It will also happen even if the blocks have a small space between them on start. However, as I said in the previous reply it is not surprising given how Pymunk and Chipmunk work.
