### ISSUE TITLE
autogeometry is slow, due to heavy use of old style callbacks and double wrapping.

### ISSUE THREAD

**Issue by Berserker66** [viblo/pymunk#126]
So, basically, autogeometry is pretty slow due to two reasons:

1. All positions are wrapped in vec2d
Ok, that's a choice I got rid of in my version, but I can see the appeal for the "pythonic" deal.

2. There are many callbacks, all of which go through the much slower old-style cffi callback system, which was replaced for precisely this use case.
Info here:
http://cffi.readthedocs.io/en/latest/using.html#extern-python-new-style-callbacks

This issue is not really for me, I already have my own function so I don't need autogeometry - but for anyone who actually uses this in their project, updating the callback style might give a decent boost.

**Comment by viblo** [comment]
Thanks for the findings. 1. is as you say for convenience, and Pymunk puts ease of use before performance. I havent looked into 2. yet, but it sounds possible. I havent used the autogeometry code a lot, so the implementation is not well tested.. I will definitely do some experiments about this.

**Comment by viblo** [comment]
Today I had some time to look into this more. The reason pymunk using old-style callbacks is because its using the ABI mode (instead of API mode). To change the code to use new style callbacks would require a change to API mode.

However, there are several advantages of ABI mode:
* Chipmunk library file (dll/so) can be compiled once per platform. This  means building binary distributions for all python versions on different OSes is much simplified compared to extension libraries.
* If you have the Chipmunk library already you dont need to have a c compiler to install or modify Pymunk. For example, you can easily add the wrapping of a missing function yourself.

**Comment by viblo** [comment]
I also made a small test with and without wrapping the positions in Vec2d. In my small example it was 2x faster with wrapping as a tuple instead of Vec2d on CPython, but the same speed on Pypy. Maybe it was a mistake to wrap it in Vec2d, if you use the resulting position directly for a segment its wasted effort with Vec2d.. However, a change would break backwards compatibility so could earliest be in a 6.0 release. I left a note in the TODO for possible things to change in a 6.x version.

**Comment by Berserker66** [comment]
Well, I was comparing the speed to not wrapping at all, just returning the v0, v1 and the point cffi objects directly. But yeah, in the end I don't mind either way, I needed my own custom function for my purpose anyway.

**Comment by viblo** [comment]
I have just released Pymunk 6.0.0. This versions have several optimizations for autogeometry with less wrapping, a removed callback and changed wrapping mode to cffi api mode. There is still a possible optimization that can be implemented on the Pymunk/C side, which can be added without changing API in a future release.
