### ISSUE TITLE
Aborting due to Chipmunk error

### ISSUE THREAD

**Issue by venkat-kittu** [viblo/pymunk#138]
when i am executing my program in windows10(64bit) and python 3.6

Aborting due to Chipmunk error: Mass must be positive and finite.
        Failed condition: 0.0f <= mass && mass < INFINITY
        Source:chipmunk_src\src\cpBody.c:257

**Comment by viblo** [comment]
What did you put mass to? Its difficult to say without seeing the code that produce the error.

**Comment by venkat-kittu** [comment]
https://github.com/harvitronix/reinforcement-learning-car/blob/master/flat_game/carmunk.py

This is the code i am using

**Comment by viblo** [comment]
It seems like it was built for Pymunk 4.x. Some breaking changes happened between the 4.x series and 5.x series of Pymunk, so you need to either update the code or use an older version of Pymunk.

I have not tried it, but from the looks of it I think the problem is the obstacles, which are created with infinite mass and moment. You can try to change https://github.com/harvitronix/reinforcement-learning-car/blob/master/flat_game/carmunk.py#L75 to `c_body =  pymunk.Body(body_type=pymunk.Body.KINEMATIC)` to make the obstacle bodies kinematic instead of dynamic and see if that helps.

**Comment by venkat-kittu** [comment]
Yeah that worked thank you
