### ISSUE TITLE
space.point_query_nearest fails when positive_y_is_up = True

### ISSUE THREAD

**Issue by ho1** [viblo/pymunk#167]
Using the constraints.py example, change positive_y_is_up = True and the hit test always returns None. 

I'm guessing the issue is here: https://github.com/viblo/pymunk/blob/f05c95ac9c6bc1fd83f7e144e81060d111d88012/pymunk/pygame_util.py#L183

**Comment by viblo** [comment]
Thanks for the report! Will take a look as soon as I have the chance.

**Comment by viblo** [comment]
The positive_y_is_up setting only affects drawing, so if you d other things you need to convert the coordinates yourself. So, if you use `positive_y_is_up = True` then you will also have to convert the mouse coordinates with the to_pymunk / from_pymunk functions before checking for hits or otherwise manipulate coordinates.
