### ISSUE TITLE
DrawOptions error with DampedSpring between Body and StaticBody

### ISSUE THREAD

**Issue by MichelangeloConserva** [viblo/pymunk#183]
Hello everyone,

my goal is to reproduce a top down physic system in which given two bodies B1 and B2, when B1 hits B2 then B2 oppose resistance and tries to get back to the initial position.

Something like this:

```
t = 0       B2      B1
t = 0       B2    B1
t = 0       B2   B1
t = 0       B2 B1
t = 0      B2B1
t = 0     B2B1
t = 0    B2B1
t = 0     B2B1
t = 0      B2B1
t = 0       B2B1
```

I managed to obtain this effect by connecting B2 with the initial position using a DampedSpring and the static body.

The code can be found at [gist link](https://gist.github.com/MichelangeloConserva/9e0fd824053c41c7fc9845a769e8b083)

This is what the result of the code looks like
![collision_test](https://user-images.githubusercontent.com/37903256/88177447-c8e9b280-cc20-11ea-95a8-ef2eb460b35b.gif)
When the body becomes green then the DumpedSpring is added.

However there is one big issue.
If I use _DrawOptions_ to draw pymunk objects then I get the following error:
```
From cffi callback <function SpaceDebugDrawOptions.__init__.<locals>.f2 at 0x7f0540918f80>:
Traceback (most recent call last):
  File "/home/michelangelo/miniconda3/envs/main/lib/python3.7/site-packages/pymunk/space_debug_draw_options.py", line 74, in f2
    Vec2d._fromcffi(a), Vec2d._fromcffi(b), self._c(color))
  File "/home/michelangelo/miniconda3/envs/main/lib/python3.7/site-packages/pymunk/pygame_util.py", line 124, in draw_segment
    p1 = to_pygame(a, self.surface)
  File "/home/michelangelo/miniconda3/envs/main/lib/python3.7/site-packages/pymunk/pygame_util.py", line 184, in to_pygame
    return int(p[0]), surface.get_height()-int(p[1])
ValueError: cannot convert float NaN to integer
```
The error happens after the springs are apped to the space.

From what I understood from the Traceback the problem is that there is a body with Vec2d(Nan,Nan) position, however I am not able to properly debug this problem.

Am I doing something wrong or is it a bug in the package?
Am I using DumpedSpring in a way it should not be used? If so, do yyou have any alternative suggestion?

Thank you very much!

Kind regards,
Michelangelo

**Comment by viblo** [comment]
Thanks for the report!

The issue seems to be that the debug drawing code cant draw a spring when both bodies in the spring is in the same position. This is definately a bug in Pymunk (or possily in the underlying Chipmunk library used by Pymunk, but the end result is the same).

Some possible workarounds:
1. Make the bodies not be the exact same position, for example by adding a small offset to the static body in `spring_to_mantain` (note that this is not a 100% certain fix, the bodes might later end up in the same position anyway):
```
if s.body.position == pos_static_body.position:
        pos_static_body.position = pos_static_body.position + (0,0.0001)
```
2. Disable drawing of constraints. You can do that with the flags property on the draw_options object. If you care too much about the constraints this is the easiest fix:
```
draw_options = DrawOptions(screen)
draw_options.flags = pymunk.SpaceDebugDrawOptions.DRAW_SHAPES | pymunk.SpaceDebugDrawOptions.DRAW_COLLISION_POINTS
```

**Comment by viblo** [comment]
I have committed a fix for this issue (So that debug drawing is more robust against Nan numbers and if they occur skip drawing that part of whatever is drawn. 

Is this critical for you? If it is I can do a new release of pymunk, otherwise I include it in the next normal release, sometime this autumn I think.

**Comment by MichelangeloConserva** [comment]
Thank you very much Victor for the swift response!

I will just modify my version of pymunk with the fix you made in the referenced commit.
It should be enough until the next release.

P.S. your package is great, keep it up with the hard work!
