### ISSUE TITLE
Vec2d usage in Pymunk - how to handle type hints and performance?

### ISSUE THREAD

**Issue by viblo** [viblo/pymunk#189]
This is a writeup of some findings, and thinking about the usage of the Vec2d class in Pymunk. (Both to help my own thinking, but also to get feedback) **Comments very welcome!**

### Background
I have rewritten the wrapping layer to use CFFI API mode, and plan to do a major release of Pymunk (6.0) when done. This will introduce several breaking changes (dropping support for Python 2 among other things), and it is therefor a good opportunity to do major changes to how Vec2d is used if needed. The development happens mainly in this branch https://github.com/viblo/pymunk/tree/cffiapi

### Type hints
I have experimented a bit with adding type hints to Pymunk. Unfortunately the state of the type checkers are not as mature as I thought and Ive hit some bugs/missing features. I have used both mypy (the leading type checker), and pyright (from MS, integrates well into VS Code). I would like to have type hints, but the type checkers has to handle them :)

1 - The type checkers cannot handle getters / setters with different types. Unfortunately this is a common pattern when using Pymunk, especially for smaller scripts:

```python
body = pymunk.Body(1,100)
body.position = (100, 100)    # position property can be set to a tuple: (100,100) 
#  (but when read out, its a Vec2d that can be used in calculations directly):
distance_to_center = body.position.get_distance( 300, 300 )
```

Current possible workarounds:
- The user of the Pymunk API ignore the type with `# type: ignore`, or just wrap everything in Vec2d. This will probably also require that the type of the properties are set to `Any` (the match everything type).

2 - Mypy does not handle `__radd__` and similar methods the same as __add__ when it comes to List[int]. I think this is a clear bug, but not a huge issue.

### Performance
1 - Every time a property of a (x,y) is set in Pymunk, its converted to a tuple, and every time its read out its converted to a Vec2d: 

```python 
def _set_position(self, pos):
    cp.cpBodySetPosition(self._body, tuple(pos))
def _get_position(self):
    return Vec2d._fromcffi(cp.cpBodyGetPosition(self._body))
```

I dont think this overhead is huge, but its there, and some user already asked to remove the Vec2d wrapping from the autogeometry code to speed it up.

2 - Im also thinking about adding some kind of batch API to Pymunk, to make it possible to for example get a list (or rather some more efficient structure, like numpy array) of body positions to make it possible to draw the state quicker. This array should then be possible to for example directly pass to a `pyglet.graphics.Batch`.

### Mutable vs Immutable
I have seen some comments that a immutable vector would be better. This could also make sense for the usage, since you cant mutate a vector that is a property anyway:

```python
>>> s = pymunk.Space()
>>> s.gravity.x
0.0
>>> s.gravity.x += 13
>>> s.gravity
Vec2d(0.0, 0.0)
```

Im leaning towards making the Vector immutable to reduce the chance of mistakes like above, but didnt decide yet.

### Ideas / options
1. Remove the Vec2d wrapping. Then it behaves more like pygame (and others).
2. Use of Vec2d always, even when setting properties (at least if type checked). 
3. Change Vec2d to be immutable. If the wrapping is kept (opt 2), then this looks like a good thing, but will require quite a bit of API changes.
4. Maybe the vector methods could be changed to be module functions and operate on tuples instead, something like 'pymunk.vec2d.add( (1,2), (3,4) )'?
5. Use a external vector class
6. Some other solution.. ? Maybe

**Comment by mikhail** [comment]
I think you discuss valid issues here. With everything moving to Python 3 I think you could continue to transition towards a more strict approach in new versions. It also seems that if you convert your vector class to a C library you'll solve some issues automatically. I've never done this so it's just a high level suggestion.

**Comment by fabiommendes** [comment]
Hello! The way I see, there are some important issues in the Vec2d and Transform classes. I was going to open separate issues, but it seems that this thread is perhaps a good place to make that discussion. I am using pymunk in a course on "Physics for Games" and sometimes those classes do not behave as expected from math definitions. As @mikhail mentioned, I also favor the transition to more strict and mathematically sound approaches in the new versions. I just want to share the issues that bother me most, but any change should be weighted with the cost of API breakage.

From a usability point of view, I would prefer Vec2d to be immutable with Pymunk accepting tuples in all places that expect vectors. This requires some wrapping and has a (perhaps non-negligible) performance cost, but makes the whole experience of using Pymunk much more Pythonic. 

That said, here is my long list of issues I see with Vec2d and Transform:

- Vec2d can add to scalars and multiply other vectors and sequences. Sometimes it behaves like an array and sometimes as a mathematical vector. I think that the array-like behavior is confusing and should be dropped.
- Vec2d accepts generic sequences in mathematical operations (like sum and subtraction), but do not check their length. This creates strange results such as  `Vec2d(1, 2) + [3, 4, 5] == Vec2d(4, 6)`
- Transform is a namedtuple while Vec2d is not. I think both should share the same base class (either tuple or object)
- By inheriting from tuples, many operations could be slightly faster. We could also limit coercion to other tuples rather than arbitrary sequence types and share implementation more easily between the op(Vec2d, Vec2d) and op(Vec2d, tuple) functions.
- Tuple deconstruction is really fast and can be about twice as fast as explicit attribute access.
- Arithmetical operators should return NotImplemented for non-supported types. Something like:
```python
def __add__(self, other):
    if isinstance(other, tuple):
        x1, y1 = self
        x2, y2 = other 
        return Vec2d(x1 + x2, y1 + y2)
     return NotImplemented
```
- Perhaps the constructor should accept only the Vec2d(x, y) signature and users could use Vec2d(*vec) to initialize with a sequence. This makes the implementation of the default constructor more efficient.
- Transform does not interact with Vec2d. Transform * Vec2d produces results, but they are mathematically meaningless. The same can be said for Transform * int and Transform + Transform.
- Transform should have convenient constructors for rotations, scale transforms, and similarity transformations in general.
- Should we consider falling back to a Cython implementation if one is available? I have an experimental project for low-dimension linear algebra lib that add vectors 6-7x as fast as Vec2d or anything we can make with pure Python. Vector operations are probably not a huge bottleneck in most operations, however.

By the way, I start my course creating a simple physics engine from scratch and then moving to Pymunk after the students have a good grasp of what the Physics engine is supposed to do and how. We implemented a Mat2 class in the math module of this project and I can "donate" it to Pymunk if there is any interest on having a matrix class to complement the linear algebra part of Pymunk. The code is in https://github.com/fisjogos-fga/demo-engine, feel free to use it!

**Comment by viblo** [comment]
@mikhail Thanks for the comment!

**Comment by viblo** [comment]
@fabiommendes Thanks for the long and detailed comment! Very good to hear about some use case and ideas to improve it. 

I will write a longer reply to you when Ive thought about the suggestions a bit more. Some are pretty straight forward, like vectors should be immutable (seems like no one wants mutable vectors). But some of the other suggestions is a bit more complex.

**Comment by viblo** [comment]
@fabiommendes Today I have looked at your suggestions a bit more in detail. 

Just to make sure I follow, in terms of operations on the vectors, you think a more limited set would be better, something like this:
```python
>>> from vec2d import Vec2d
>>> v1 = Vec2d(1,2)
>>> v2 = Vec2d(3,4)
# Addition
>>> v1 + v2
Vec2d(4, 6)
>>> v1 + (3,4)
Vec2d(4, 6)
>>> (1,2) + v2
Vec2d(4, 6)

# Subtraction
>>> v1 - v2
Vec2d(-2, -2)
>>> v1 - (3,4)
Vec2d(-2, -2)
>>> (1,2) - v2
Vec2d(-2, -2)

# Multiplication
>>> v1 * 2
Vec2d(2, 4)
>>> 2 * v1
Vec2d(2, 4)

# Division
>>> v1 / 2
Vec2d(0.5, 1.0)
>>> v1 // 2
Vec2d(0, 1)

# Mod & divmod: removed
# Pow: removed
# Bitwise (<< >> & | ^)

# Negate
>>> -v1
Vec2d(-1, -2)

# Unary Pos: removed

# Abs
>>> abs(Vec2d(1, -2))
Vec2d(1, 2)

# Invert (__invert__ magic): removed
```
In general I think it sounds good. The reason why there are so many supported cases is that the vector class used as inspiration for Vec2d had them.. In the worst case someone want something its always possible to add back later if its justified.

**Comment by viblo** [comment]
Regarding Transforms: 

1. Extending them with some helper functions for scale, rotate and translate are a great idea. I also have to think carefully when I need a transform. Will at it to the todo list.

2. Do you have some example of when its useful to do add or multiplication with transforms and vectors? And I wonder if using the __matmul__ operator would be good for that case?

3. Regarding the base class of Transform / Vec2d, does it matter if they are different? :)

**Comment by viblo** [comment]
**Vector coercion / base class**

This is something Ive been thinking about.. When adding types the most basic type is `Sequence[float]`, but sequence does not have a length specified which is not optimal. Would be much cleaner if the type could be specified as `Tuple[float, float]` only.

At the same time, in my own code, and in many of the Pymunk examples lists are used instead of a tuple or Vec2d. So maybe such a change would have a big impact on existing code / users..

What do you think about this?

**Comment by viblo** [comment]
**Pluggable vector?**

While thinking more about the vector issues, and their most common usage it hit me that maybe one solution would be to make the vector class pluggable? Pymunk as such only use Vec2d internally to a minimal amount (since all the actual calculations are done in C code, which uses a different Vector..).

Each time a Vec2d is returned from Pymunk and it comes from the c side/cffi it does `Vec2d(c-struct.x, c-struct.y)`. Each time a argument v is passed in as a Vec2d to a Pymunk function, Pymunk will do `tuple(given_variable)`. Given that a vector class supports this interface, and you could somehow let the user override it when importing pymunk I think it could work.

Some pros/cons:
1. Possibly confusing when sharing code using Pymunk with different vector types
2. Pymunk becomes a bit more complex
3. Easier interop with other libraries with their own vector classes
4. Allows for better performing Vector classes, without any compromises or changes from Pymunk

Does this sound like a good idea?

**Comment by fabiommendes** [comment]
> @fabiommendes Today I have looked at your suggestions a bit more in detail.
> 
> Just to make sure I follow, in terms of operations on the vectors, you think a more limited set would be better, something like this:
> 
> ```python
> >>> from vec2d import Vec2d
> >>> v1 = Vec2d(1,2)
> >>> v2 = Vec2d(3,4)
> # Addition
> >>> v1 + v2
> Vec2d(4, 6)
> >>> v1 + (3,4)
> Vec2d(4, 6)
> >>> (1,2) + v2
> Vec2d(4, 6)
> 
> # Subtraction
> >>> v1 - v2
> Vec2d(-2, -2)
> >>> v1 - (3,4)
> Vec2d(-2, -2)
> >>> (1,2) - v2
> Vec2d(-2, -2)
> 
> # Multiplication
> >>> v1 * 2
> Vec2d(2, 4)
> >>> 2 * v1
> Vec2d(2, 4)
> 
> # Division
> >>> v1 / 2
> Vec2d(0.5, 1.0)
> >>> v1 // 2
> Vec2d(0, 1)
> 
> # Mod & divmod: removed
> # Pow: removed
> # Bitwise (<< >> & | ^)
> 
> # Negate
> >>> -v1
> Vec2d(-1, -2)
> 
> # Unary Pos: removed
> 
> # Abs
> >>> abs(Vec2d(1, -2))
> Vec2d(1, 2)
> 
> # Invert (__invert__ magic): removed
> ```
> 
> In general I think it sounds good. The reason why there are so many supported cases is that the vector class used as inspiration for Vec2d had them.. In the worst case someone want something its always possible to add back later if its justified.

Yes, I think it would be cleaner to restrict to vector algebra functions instead of mixing vectors with arrays. The only change I would make is to take abs(vec) ==  vec.length, so we interpret absolute value as "norm" rather than a elementwise operation. This makes code like `abs(u - v) < tol` to work with both vectors and numbers and I don't see so many use cases for mapping the abs function to components. Perhaps +vec should return the vector as is (or a copy if it is mutable), in a analogy with numbers.

**Comment by fabiommendes** [comment]
> **Transforms**
> 
> 1. Extending them with some helper functions for scale, rotate and translate are a great idea. I also have to think carefully when I need a transform. Will at it to the todo list.
> 2. Do you have some example of when its useful to do add or multiplication with transforms and vectors? And I wonder if using the **matmul** operator would be good for that case?
> 3. Regarding the base class of Transform / Vec2d, does it matter if they are different? :)

1) The only usage of Transform I found is in Shape.update(transform), which redirects to C code and update a shape. I think it feels very natural to interact with vectors and even doing basic arithmetic with transforms by interpreting them as extended matrices. I confess that right now I am using them more to teach linear algebra than to actually implementing games ;)

2) I agree that matmul is probably a better operator, while mul should be kept only for scalar multiplication. The way it is now is weird, because Transform is interpreted as a sequence and Vec2d computes the piecewise multiplication with the first 2 components.

As for algebraic operations with Transforms, they can be interpreted just like matrices: multiplication combines transforms, i.e.: `T1 @ T2` creates a new transform that applies T2 and then T1 to a vector and `T1 + T2` applies T1 and T2 to the same vector and then combine results with addition (which is a bit convoluted, but can be useful to construct complex transformations). So, if T represents a camera, we can the view area, or scale by simply multiplying by the corresponding operation, like so `T = T_shift @ T`.

3) They can definitely have different base classes. I just think that NamedTuple fits Vec2d much more naturally than Transform. So, if we are OK with named tuples, they should probably be used in both cases for the sake of consistency. I understand that they cannot be used in Vec2d right now because Vec2d is mutable.

**Comment by fabiommendes** [comment]
> **Vector coercion / base class**
> 
> This is something Ive been thinking about.. When adding types the most basic type is `Sequence[float]`, but sequence does not have a length specified which is not optimal. Would be much cleaner if the type could be specified as `Tuple[float, float]` only.
> 
> At the same time, in my own code, and in many of the Pymunk examples lists are used instead of a tuple or Vec2d. So maybe such a change would have a big impact on existing code / users..
> 
> What do you think about this?

I prefer limiting to tuples precisely because of that: Python has no notion of Sequence[float, 2], while tuples are philosophically a compound type rather than a sequence (and type checkers understand this).  However, I understand that it will break a lot of code if it is suddenly changed to this more strict behavior. This is made worst because `vec = [x, y]` is arguably closer to mathematical notation than `vec = (x, y)`, so it is something that people will likely default to.

Maybe a good compromise would be to issue deprecation warnings and check only if len(seq) == 2 and change behavior after pymunk 7+ or some milestone well into the future. What do you think about this?

**Comment by fabiommendes** [comment]
> **Pluggable vector?**
> 
> While thinking more about the vector issues, and their most common usage it hit me that maybe one solution would be to make the vector class pluggable? Pymunk as such only use Vec2d internally to a minimal amount (since all the actual calculations are done in C code, which uses a different Vector..).
> 
> Each time a Vec2d is returned from Pymunk and it comes from the c side/cffi it does `Vec2d(c-struct.x, c-struct.y)`. Each time a argument v is passed in as a Vec2d to a Pymunk function, Pymunk will do `tuple(given_variable)`. Given that a vector class supports this interface, and you could somehow let the user override it when importing pymunk I think it could work.
> 
> Some pros/cons:
> 
> 1. Possibly confusing when sharing code using Pymunk with different vector types
> 2. Pymunk becomes a bit more complex
> 3. Easier interop with other libraries with their own vector classes
> 4. Allows for better performing Vector classes, without any compromises or changes from Pymunk
> 
> Does this sound like a good idea?

I think this requires some experimentation and benchmarks before becoming official, but can be a very nice feature if we find great performance benefits in some use cases. I think with enough Python trickery and monkey patching it should be already possible to change Vec2d by a different class in runtime. Perhaps we could design some benchmarks to test the idea before committing to much effort to it.

**Comment by viblo** [comment]
> 
> 
> > @fabiommendes Today I have looked at your suggestions a bit more in detail.
> > Just to make sure I follow, in terms of operations on the vectors, you think a more limited set would be better, something like this:
> > ```python
> > >>> from vec2d import Vec2d
> > >>> v1 = Vec2d(1,2)
> > >>> v2 = Vec2d(3,4)
> > # Addition
> > >>> v1 + v2
> > Vec2d(4, 6)
> > >>> v1 + (3,4)
> > Vec2d(4, 6)
> > >>> (1,2) + v2
> > Vec2d(4, 6)
> > 
> > # Subtraction
> > >>> v1 - v2
> > Vec2d(-2, -2)
> > >>> v1 - (3,4)
> > Vec2d(-2, -2)
> > >>> (1,2) - v2
> > Vec2d(-2, -2)
> > 
> > # Multiplication
> > >>> v1 * 2
> > Vec2d(2, 4)
> > >>> 2 * v1
> > Vec2d(2, 4)
> > 
> > # Division
> > >>> v1 / 2
> > Vec2d(0.5, 1.0)
> > >>> v1 // 2
> > Vec2d(0, 1)
> > 
> > # Mod & divmod: removed
> > # Pow: removed
> > # Bitwise (<< >> & | ^)
> > 
> > # Negate
> > >>> -v1
> > Vec2d(-1, -2)
> > 
> > # Unary Pos: removed
> > 
> > # Abs
> > >>> abs(Vec2d(1, -2))
> > Vec2d(1, 2)
> > 
> > # Invert (__invert__ magic): removed
> > ```
> > 
> > 
> > In general I think it sounds good. The reason why there are so many supported cases is that the vector class used as inspiration for Vec2d had them.. In the worst case someone want something its always possible to add back later if its justified.
> 
> Yes, I think it would be cleaner to restrict to vector algebra functions instead of mixing vectors with arrays. The only change I would make is to take abs(vec) == vec.length, so we interpret absolute value as "norm" rather than a elementwise operation. This makes code like `abs(u - v) < tol` to work with both vectors and numbers and I don't see so many use cases for mapping the abs function to components. Perhaps +vec should return the vector as is (or a copy if it is mutable), in a analogy with numbers.

Ah right. Yeah, I can definately see why abs should return the length :) It will create a difficult to spot breaking API change, but I have never seen any code using abs(vec) anyway, so should be safe. I guess +vec can stay, it doesnt do anything, so guess noone will ever call it, but since  unary + is defined for normal floats as well with the same reasoning it kinda make sense.

**Comment by viblo** [comment]
> 
> 
> > **Transforms**
> > 
> > 1. Extending them with some helper functions for scale, rotate and translate are a great idea. I also have to think carefully when I need a transform. Will at it to the todo list.
> > 2. Do you have some example of when its useful to do add or multiplication with transforms and vectors? And I wonder if using the **matmul** operator would be good for that case?
> > 3. Regarding the base class of Transform / Vec2d, does it matter if they are different? :)
> 
>     1. The only usage of Transform I found is in Shape.update(transform), which redirects to C code and update a shape. I think it feels very natural to interact with vectors and even doing basic arithmetic with transforms by interpreting them as extended matrices. I confess that right now I am using them more to teach linear algebra than to actually implementing games ;)

The other use case is when creating a Poly shape, then the transform can be passed in for the polygon vertices. I have to think about how far to take it.. I can imagine at least one case where its directly useful, to call `transform @ vec` from the prompt to see what the result is without having to create a poly shape.

> 
>     2. I agree that matmul is probably a better operator, while mul should be kept only for scalar multiplication. The way it is now is weird, because Transform is interpreted as a sequence and Vec2d computes the piecewise multiplication with the first 2 components.

Yeah, its a side effect of it being a (named) tuple. You can also add a tuple and a transform if you want.. Maybe dataclass would be a better fit (but with some other effects). 

> 
> 
> As for algebraic operations with Transforms, they can be interpreted just like matrices: multiplication combines transforms, i.e.: `T1 @ T2` creates a new transform that applies T2 and then T1 to a vector and `T1 + T2` applies T1 and T2 to the same vector and then combine results with addition (which is a bit convoluted, but can be useful to construct complex transformations). So, if T represents a camera, we can the view area, or scale by simply multiplying by the corresponding operation, like so `T = T_shift @ T`.
> 
>     1. They can definitely have different base classes. I just think that NamedTuple fits Vec2d much more naturally than Transform. So, if we are OK with named tuples, they should probably be used in both cases for the sake of consistency. I understand that they cannot be used in Vec2d right now because Vec2d is mutable.

Right. I noticed some other limitation of NamedTuple recently when adding type hints, so lets see.

**Comment by viblo** [comment]
> 
> 
> > **Vector coercion / base class**
> > This is something Ive been thinking about.. When adding types the most basic type is `Sequence[float]`, but sequence does not have a length specified which is not optimal. Would be much cleaner if the type could be specified as `Tuple[float, float]` only.
> > At the same time, in my own code, and in many of the Pymunk examples lists are used instead of a tuple or Vec2d. So maybe such a change would have a big impact on existing code / users..
> > What do you think about this?
> 
> I prefer limiting to tuples precisely because of that: Python has no notion of Sequence[float, 2], while tuples are philosophically a compound type rather than a sequence (and type checkers understand this). However, I understand that it will break a lot of code if it is suddenly changed to this more strict behavior. This is made worst because `vec = [x, y]` is arguably closer to mathematical notation than `vec = (x, y)`, so it is something that people will likely default to.
> 
> Maybe a good compromise would be to issue deprecation warnings and check only if len(seq) == 2 and change behavior after pymunk 7+ or some milestone well into the future. What do you think about this?

Yes, I agree that getting rid of list would be nice. But have to think about it some more first. My feeling is that many libraries accept lists & tuples even when only tuples would be more appropriate.

One additional idea I had was to let the code could accept lists as you say, but the type hint for any arguments be `Union[Vec2d, Tuple[float, float]]`. Then any old code will work fine, but new code contain strong hints to what to use.

**Comment by viblo** [comment]
> 
> 
> > **Pluggable vector?**
> > While thinking more about the vector issues, and their most common usage it hit me that maybe one solution would be to make the vector class pluggable? Pymunk as such only use Vec2d internally to a minimal amount (since all the actual calculations are done in C code, which uses a different Vector..).
> > Each time a Vec2d is returned from Pymunk and it comes from the c side/cffi it does `Vec2d(c-struct.x, c-struct.y)`. Each time a argument v is passed in as a Vec2d to a Pymunk function, Pymunk will do `tuple(given_variable)`. Given that a vector class supports this interface, and you could somehow let the user override it when importing pymunk I think it could work.
> > Some pros/cons:
> > 
> > 1. Possibly confusing when sharing code using Pymunk with different vector types
> > 2. Pymunk becomes a bit more complex
> > 3. Easier interop with other libraries with their own vector classes
> > 4. Allows for better performing Vector classes, without any compromises or changes from Pymunk
> > 
> > Does this sound like a good idea?
> 
> I think this requires some experimentation and benchmarks before becoming official, but can be a very nice feature if we find great performance benefits in some use cases. I think with enough Python trickery and monkey patching it should be already possible to change Vec2d by a different class in runtime. Perhaps we could design some benchmarks to test the idea before committing to much effort to it.

I did a quick validation tests, with two minimal changes to the Vec2d code it could be swapped out at runtime for at least `pygame.math.Vector` without issues (but I did not tests performance). From the looks of it I dont think supporting such a plugin system would create much worse performance than currently in Vector creation from cffi types. 


The big advantage I see is that with this change Pymunk could adapt the vector class already in use. So for example, if you already use Pygame you can easily configure it to use the Pygame Vector class which you might already use in other Pygame code. Or if you have a more comprehensive library, like your euclid library, you can use that everywhere without manual conversion to/from Pymunk Vec2ds. That you currently end up with several different Vector classes in your code if its somewhat complex is not optimal.  

The downside is mostly about confusion/complexity. If you write code with your own Vector library and something doesnt work it might be more tricky to find the root cause. Same when sharing code, wont be very easy to see what actual type is returned as a body position unless you have the full code including any override which likely is in the very top. I still have an internal debate about how important the downside is, so any comments here is very appreciated :)

I should also add that in Chipmunk (the c library Pymunk uses) there is already a vector "class", but since it cant be wrapped to a pythonic class with CFFI the Vec2d class had to be pure Python. I would not like to add another wrapping method in addition to CFFI, especially when neither Cython nor Python Extensions work that well in Pypy. They run, but performance is not so good.. Anyway, if the Vector class was swappable it wouldnt be an issue, a user that knows they will only use CPython can use a Cyhtonised class and so on.

**Comment by viblo** [comment]
A small update in case someone is following this thread: I have made performance experiments with a batching API , and the gains are massive when the number of objects are 10+. This is good for several reasons. 

It validates the initial assumption that its a good idea to migrate to CFFI API mode. It also means that the performance of a single `Vec2d` becomes less important, in cases where a lot of objects are handled a batched API could be used to extract it all out into a numpy array (or similar) and do the calculations there. However, the other parts are of course still very important, like the API cleanup, type hints and usability.

**Comment by viblo** [comment]
Thanks for the input. Pymunk 6.0.0 is now released so will close this issue. I think it turned out ok :) but is of course room for more improvements in the future. Also, if you have any other comments around Pymunk dont be shy to tell me, for example with a issue here on Github. No promise, but its very helpful to get real usage feedback!
