### ISSUE TITLE
Screenshot for using PySimpleGUI with pymunk

### ISSUE THREAD

**Issue by PySimpleGUI** [viblo/pymunk#191]
A long time ago I integrated pymunk with [PySimpleGUI](http://www.PySimpleGUI.com) to make some examples of how to graph objects with the help of a physics engine. 

The result is a "Simple" bouncing balls simulation.

Then I combined it with some magic that I'm able to do with PySimpleGUI.  On Windows, it's possible to make portions of windows entirely transparent.  You can click through the transparent parts to the underlying windows/desktop.

I made a giant, screen-sized window, made the background transparent, and released a LOT of balls.  The effect is that there are balls bouncing all over my desktop.

It's a little laggy looking mostly because the ShareX screen capture software struggles a bit to capture the screen as a GIF.

![0AGFpXaTTa](https://user-images.githubusercontent.com/46163555/95880164-37806d00-0d45-11eb-81f9-a0b469ed2b44.gif)

What I find amazing about this demo and pymunk is that each ball is individually controlled.  On each update, every ball's new location is computed and the ball is moved slightly.  

Congrats on making a nice Python package and thanks for updating it.

**Comment by viblo** [comment]
Very cool! 
Had to try it myself, runs nice on my laptop as long as I can hold myself from adding too many balls :) I think these kinds of demos that interacts with the desktop (even if its just transparency) always feel very cool.

I noticed one small issue, the balls become a little bit misaligned when relocated, since the Relocate method uses top left as origin. I think you should to subtract with the ball radius to make it correct. For example like this:
```python
graph_elem.RelocateFigure(
    ball.gui_circle_figure,
    ball.body.position[0] - ball.shape.radius,
    ball.body.position[1] - ball.shape.radius,
)
```

**Comment by viblo** [comment]
Forgot to add, I will add it to the showcase page of pymunk.org next time I update it. Its always great to hear/see usages of Pymunk!
