### ISSUE TITLE
Disabling chipmunk printout running game with newer versions of PyMunk

### ISSUE THREAD

**Issue by justinkterry** [viblo/pymunk#195]
By default with PyMunk, you used to be able to suppress the `Loading chipmunk for Linux (64bit) [/home/justinkterry/.local/lib/python3.6/site-packages/pymunk/libchipmunk.so]` with 

```
import pymunkoptions
pymunkoptions.options["debug"] = False
import pymunk
```

However pymunk options no longer works with neer versions of PyMunk. How can this be done with newer versions? I don't see guides on the internet anywhere.

**Comment by viblo** [comment]
The new version of pymunk does not print anything when loading, so the option was removed. 

Longer explanation: With the latest version of pymunk there is no external .so file like in previous versions (since Pymunk changed how it is using cffi to call the c library chipmunk). Instead Chipmunk is compiled to a "normal" python extension which is loaded by cffi. With the previous way Pymunk itself had some logic to find the library (.so) and load it, but now cffi is doing it. Because of that it didnt feel necessary to print the path to the extension.

**Comment by justinkterry** [comment]
Version 5.7.0 doesn't have pymunkoptions, and is still gives all this when I import it:

Loading chipmunk for Linux (64bit) [/home/justinkterry/.local/lib/python3.6/site-packages/pymunk/libchipmunk.so]
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

**Comment by viblo** [comment]
Oh.. that was strange. When I install it from pip it works as expected.

How did you install pymunk, and how do you run it?

**Comment by justinkterry** [comment]
`pip3 install pymunk` to install. You can just get the error like:

```
justinkterry@prophet:~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymunk
Loading chipmunk for Linux (64bit) [/home/justinkterry/.local/lib/python3.6/site-packages/pymunk/libchipmunk.so]
```

Upgrading from pymunk 5.7.0 to 6.0.0 actually fixes this error though (the ALSA thing is coming from pygame). Would it be possible to do a 5.7.1 release fixing this? I'm using this in a library of games for machine learning to play (https://github.com/PettingZoo-Team/PettingZoo), so if that changes I have to bump environment versions (which I try to avoid when possible)

**Comment by viblo** [comment]
I can definitely make a fix release if needed. However, I still do not understand exactly what is wrong / where the problem lies.

So, if you do `import pymunkoptions` you immediately get `Loading chipmunk for Linux (64bit) [/home/justinkterry/.local/lib/python3.6/site-packages/pymunk/libchipmunk.so]`?

**Comment by justinkterry** [comment]
So I was wrong about the issue, I did something stupid in my docker config. My apologies.
