### ISSUE TITLE
Error creating Ruler with Measurements in Pymunk- Recursion

### ISSUE THREAD

**Issue by ifeoluwatayo** [viblo/pymunk#196]
I am trying to write a program with pymunk that shows a vertical ruler on the screen. The ruler is however showing at runtime and not on the screen created with pymunk. the code is shown below. Kindly help me out with this issue.

       `import sys, random
        import pygame
        from pygame.locals import *

        import pymunk
        import pymunk.pygame_util
        from random import seed
        from random import choice

        class EnglishRuler:
              def __init__(self,num_inches, major_length):
                    self.__num_inches = num_inches
                    self.__major_length = major_length
              def draw_line(self,tick_length, tick_label=''):
                     line ='-'*tick_length
                     if tick_label:
                          line += ''+tick_label
                     print(line)
              def draw_interval(self, center_length):
                     if center_length>0:
                          self.draw_interval(center_length - 1)
                          self.draw_line(center_length)
                          self.draw_interval(center_length - 1)
              def draw_ruler(self):
                    self.draw_line(self.__major_length, '0')
                    for j in range(1, 1+self.__num_inches):
                          self.draw_interval(self.__major_length- 1)
                          self.draw_line(self.__major_length, str(j))
    
       def main():
            pygame.init()
            screen = pygame.display.set_mode((600, 600))
            pygame.display.set_caption("Experiments")
            clock = pygame.time.Clock()

            space = pymunk.Space()
            space.gravity = (0.0, -900.0)

           ruler = EnglishRuler(4,5)
           ruler.draw_ruler()

           while True:
                 draw_options = pymunk.pygame_util.DrawOptions(screen)

                 screen.fill((0,255,255))

                 space.debug_draw(draw_options)
                 space.step(1/50.0)
                 pygame.display.flip()
                 clock.tick(5)    
       if __name__ == '__main__':
              main()`

**Comment by viblo** [comment]
I think the problem is that you draw the rules once, just before the while loop. Then inside the while loop you will fill the screen (overwrite the ruler) each loop, and then draw the pymunk space. Just move ruler.draw_ruler() to after screen.fill and see if it works better

**Comment by ifeoluwatayo** [comment]
Thank you. I have tried to move the ruler method to after screen.fill as suggested. The measurement is however still showing on the python shell and not on the pymunk screen. I had to force-end the program since the while loop continually calls the ruler method. I hope there will be another way around this.

**Comment by viblo** [comment]
Ah, now I see. Didnt read your ruler class very carefully, only checked the drawing call :)

That is because you are not drawing the ruler to the `screen`, you are printing it to the shell (in the draw_line method). Pymunk on the other hand draws to the pygame `screen`, since you are using `pymunk_util.DrawOptions`. What you need to do is rewrite the ruler class do its drawing using Pygame and not print the ruler to the shell.

This is not really related to Pymunk, and is quite fundamental to understanding how Pygame works but a little out of scope of the help I can provide here. 
Instead I think your best idea would be to either try to read up a bit more of how Pygame works, maybe follow a tutorial or some book like http://inventwithpython.com/pygame/  Or you could try go to the python discord chat, and ask for help in one of the help rooms: https://discord.gg/python which seems to be quick to help.

**Comment by ifeoluwatayo** [comment]
Thank you. I will check the links attached.
