### ISSUE TITLE
 pyglet_util debug_draw pyglet 2.0 compatibility

### ISSUE THREAD

**Issue by n00b001** [viblo/pymunk#220]
pymunk==6.3.0, pyglet==2.0.0, python==3.10

when using pyglet_util and debug_draw I get the following error:
AttributeError: 'Batch' object has no attribute 'add'

This is because pyglet has a breaking change from 1.5.x to 2.x:
https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html#graphics-module

"batch" no longer has the method "add".

I am new to pymunk/pygame/pyglet and I have been following the tutorials but have been left very confused as to why I'm getting this error - I've finally found out why!

I'm keen to see when pymunk will support pyglet 2.x!

**Comment by viblo** [comment]
Thanks for the report! Yes, this is a known issue, as seen here https://github.com/viblo/pymunk/issues/202
At least now Pymunk is using the shapes functions, and not calling gl-methods directly, so the actual work left should not be too much.  However, what Im thinking about is how to do upgrade, since many people might still be using the older 1.5 branch of pyglet.
 
Anyway, I will close this issue since there's already existing one. But you are very welcome with comments there if you have opinions on the matter.
