### ISSUE TITLE
NaN for vertex data in debug_draw starting at 3rd frame

### ISSUE THREAD

**Issue by nrichards** [viblo/pymunk#226]
Gist illustrating issue: https://gist.github.com/nrichards/03f43916fd409b07de14e77f28af0044
Possible related issue: #183 

Hi! Fantastic and fun Python tool. ⭐

The `debug_draw` function appears to be able to lose track of vertex data in the above-linked case, for a Body with a DYNAMIC type. Changing to KINEMATIC shows no issue. First two frames do not draw, and log NO errors. Third frame logs this:

```
Exception ignored from cffi callback <function ext_cpSpaceDebugDrawPolygonImpl at 0x106d2e820>:
Traceback (most recent call last):
  File "/Users/nick/proj/python/pendulum2d/venv/lib/python3.9/site-packages/pymunk/_callbacks.py", line 122, in ext_cpSpaceDebugDrawPolygonImpl
    options.draw_polygon(vs, radius, options._c(outline_color), options._c(fill_color))
  File "/Users/nick/proj/python/pendulum2d/venv/lib/python3.9/site-packages/pymunk/pygame_util.py", line 189, in draw_polygon
    def draw_polygon(
  File "/Users/nick/proj/python/pendulum2d/venv/lib/python3.9/site-packages/pymunk/pygame_util.py", line 196, in <listcomp>
    ps = [to_pygame(v, self.surface) for v in verts]
  File "/Users/nick/proj/python/pendulum2d/venv/lib/python3.9/site-packages/pymunk/pygame_util.py", line 227, in to_pygame
    if positive_y_is_up:
ValueError: cannot convert float NaN to integer
```

I am a noob, learning pymunk, and making a big pile of bricks (DYNAMIC) which I intend to knock over using a ball projectile. 

I could workaround this by using only pygame drawing API.

**Comment by viblo** [comment]
The reason why it happens is that the bricks doesnt have any mass or moment set. Objects without mass (or with infinite mass) behave very strangely, just as you could imagine a 0 mass object would in real life :)

To fix it I suggest you set a mass on the brick_shape shape. For example `brick_shape.mass = 1`. http://www.pymunk.org/en/latest/pymunk.html#pymunk.Body.__init__ 

This is also the reason why I havent tried so hard to fix the NaN drawing issue, since its a very good indication of something bad/strange happening, and just hiding the error would likely lead to an even more difficult to understand error a little later.
 Since you are not the first one to experience this I wonder if I should add a better error text or even outright preventing 0 or inf mass of objects added to a space.

**Comment by nrichards** [comment]
That fixes this. Thank you @viblo for the explanation and fix: _Aww yiss, massless physics. !Noob alert!_ I'll be happily using `debug_draw` shortly.

<img src="https://user-images.githubusercontent.com/704698/226211715-ff0dd366-943d-4a22-8208-8e2488ed1223.png" width="100" />

Re **future**: perhaps `"Does Shape have a reasonable mass?"` + the prior ValueError exception message? Adding guidance text to the current [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) could be useful for a noob like me. This usage-error occurred when I naively, trivially set a KINEMATIC to be DYNAMIC.

Q: Where would you prefer it to be in the call-stack? `ext_cpSpaceDebugDrawPolygonImpl` ? According to [comments on StackOverflow](https://stackoverflow.com/a/68408809/915990), an untriggered `try:` is low-cost, performance wise.
