### ISSUE TITLE
Pymunk: Issue with Removing Constraints from Body

### ISSUE THREAD

**Issue by BenjaminKerbal** [viblo/pymunk#229]
Hello,

I'm currently developing a physics simulation using Pymunk, where I often need to remove constraints from bodies. I've noticed an unexpected behavior that I hope someone can help me with.

When I remove a constraint from the Space using **space.remove(constraint)**, the constraint is successfully removed from the simulation. However, the Body that was associated with this constraint still has this constraint present in its **body.constraints** set. 

After the **space.remove(constraint)** call, I'd expect **constraint** to no longer appear in **body.constraints**, however, it's still present. I've tried using **body.remove(constraint)**, but this doesn't work as the Body class doesn't have a working **remove** method.

This issue is causing my **body.constraints** set to grow over time, even though most of the constraints in it have been removed from the space. Over time, I'm concerned that this could impact the performance of my simulation.

Am I doing something wrong here, or is this a bug in Pymunk? Is there a way to directly remove a constraint from a Body, or to ensure that when a constraint is removed from the Space, it is also removed from the associated Body's **body.constraints** set?

Thank you in advance for any help you can provide.

**Comment by viblo** [comment]
Good question! 
So,  when you create a constraint you assign it to two bodies, like `j = pymunk.PinJoint(body1, body2)`. At this point the constraint object will keep a reference to the bodies (this is not exposed in the API). For convenience its also possible to get the constraint(s) out from the body, with `body.constraints` as you write. If the constraint is not needed anymore and all references to it are deleted, then the reference between the constraint and body will also be cleaned up eventually (behind the scenes its implemented as a weakset, so this cleanup depends on the garbage collector).

```
>>> import pymunk
>>> b1 = pymunk.Body()
>>> b2 = pymunk.Body()
>>> j = pymunk.PinJoint(b1, b2)
>>> b1.constraints
{<pymunk.constraints.PinJoint object at 0x0000019DAC940F50>}
>>> del j
... some other code that triggers garbage collection
>>> b1.constraints
set()
```
Note that the space is not involved here. The constraint - body reference can exist outside the space. (but of course, the constraint wont be cleaned up while the constraint and body are in the space since the space will keep a reference to the constraint)

**Comment by BenjaminKerbal** [comment]
Hello,

Thank you for the detailed explanation. This clarifies how constraints are managed in Pymunk, and why the constraints remain in **body.constraints** even though they have been removed from the space.  I will take your advice and ensure all references to constraints are removed when they are no longer needed.

**Comment by viblo** [comment]
Great! I made a small improvement to the docs as well.
