### ISSUE TITLE
Body or shape identification in collision handler callback

### ISSUE THREAD

**Issue by AmoryR** [viblo/pymunk#230]
### Context

I'm creating a game where ball hit a box and it adds point to a player.

### Code

A player has a name and a ball

```
class Player:
    name: str
    ball: Pymunk.Circle

    def __init__(self, name: str):
        self.name = name
        body = pymunk.Body(1, 100, body_type=pymunk.Body.DYNAMIC)
        body.position = (0,0)
        
        self.ball = pymunk.Circle(body, 10)
        self.ball.collision_type = 1
        space.add(body, self.ball)
```

I create a box that can be hits by a ball

```
box_body = pymunk.Body(body_type=pymunk.Body.STATIC)
box_body.position = (100, 200)
box = pymunk.Poly.create_box(box_body, (100, 100))
box.collision_type = 2
space.add(box_body, box)
```

I instantiate a list of players and I use Pygame to show the balls for each players.

Then I create the collision handler

```
def handle_collision(arbiter, space, data):
    # Here I use the arbiter to get the ball and box shape
    # But I did not find a way to know to which player the ball is associate

handler = space.add_collision_handler(1, 2)
handler.begin = handle_collision
```

Every things work fine but ...

### Question

How can I identify the ball to know to which player it is associated in the collision handler callback ?

**Comment by viblo** [comment]
Here are two options:
1. Add a property to the pymunk shape with the player.
```
class Player:
    ...
    def __init__(self, name: str):
        ...
        self.ball = pymunk.Circle(body, 10)
        self.ball.player = self
        ...

# Then when you have the shape, you can just check if it has a player and if so get it out
if hasattr(shape, "player"):
    player = shape.player
```
A note here, this will create a circular reference (player has a ball, and ball has a player), which means it can be difficult for the garbage collector to clean it up when they are not used anymore (if there are no __del__ methods it should work, otherwise you might need a weak ref). 

2. Loop through all your players and check which one the shape belongs to, like this
```
found_player = None
for player in list_of_players:
    if player.ball == shape:
        found_player = player
        break
...
if found_player != None:
    # do something with the player
```
If there's only 2 players maybe this is the quicker and easier option, especially if the shapes will always belong to a player.

**Comment by AmoryR** [comment]
Options one works well.

I added an ID for each player and add a property to the pymunk shape.

In `Player`:

`self.ball.shape.player_id = self.id`

Then I can get the player id in the collision handler as you said.

Thanks ;)
