### ISSUE TITLE
Moving too fast leads to a series of problems such as through walls

### ISSUE THREAD

**Issue by Python-ZZY** [viblo/pymunk#231]
When I run examples/arrow.py, I shoot the arrows on the ground, then pick them up with the archery tool to fire them at maximum speed, then a lot of bugs appear and exit the program.
When i run constraints.py, I moved the bodies very fast and then they went through walls.

**Comment by viblo** [comment]
Thanks for the report! In general the examples are not designed to be fool proof and cover everything you might want from a complete app or game, instead I have tried to make them simple and show one way to do something, and serve as inspiration. 

However, both your findings are quite reasonable and easy to fix. I have updated them to restrict the angle allowed in arrow.py and lower the force used by the mouse constraint in constraints.py so that you cannot drag the objects fast enough.
