### ISSUE TITLE
Faster way for getting Polygon vertices in world coordinates

### ISSUE THREAD

**Issue by rdesc** [viblo/pymunk#242]
Hi, thank you for the awesome work on a python wrapper for chipmunk2D.

I just had a question regarding getting vertices of many Polygon objects, i.e. with [get_vertices()](https://www.pymunk.org/en/latest/pymunk.html#pymunk.Poly.get_vertices)

Is there a faster way of getting these vertices in world coordinates? I have on the order of 1000 polygons part of my simulation that all need to be rendered during each frame update and getting the updated vertices seems to be really really slow -- around 100 ms  in total for the 1000+ polygons where for each polygon `get_vertices()` is called and vertices are transformed to global coordinates. Half the time seems to be spent on the actual `get_vertices()` call. Below is the small helper function I use 

````
def get_obs_from_poly(polygons: List):
    return [
        np.asarray(poly.get_vertices()) @ Rxy(poly.body.angle).T + poly.body.position
        for poly in polygons
    ]
````

Thanks for the help!

**Comment by rdesc** [comment]
Hi, I'm answering my own question haha. Best option I think is to simply get these vertices once at the start of the simulation and then use those throughout the rest of the sim, instead of calling `get_vertices()` each sim step. Let me know if you have any additional thoughts on this but I will close for now.

**Comment by viblo** [comment]
Happy you figured it out :) 
Looks like you found a good way, only call it once at the start. There will always be overhead to call functions that internally call Chipmunk, so its best to avoid if possible. 

In this specific case, since you know the vertices (since you created the Poly shape to begin with), I suspect you could just use that and not call `get_vertices` at all, but the end result will be more or less the same..

On the topic of performance I want to point out that the latest Pymunk version contains an (experimental) batch API that might help as well. Using that you can fetch all positions and angles in a single call which depending on the case and what you do with it can give a nice performance increase. (Downside is mainly that its experimental, but also more cumbersome than the normal way)

**Comment by rdesc** [comment]
Yes, I was planning on taking a look at the batch API :) Thanks!
