### ISSUE TITLE
Batch api for applying impulse

### ISSUE THREAD

**Issue by rdesc** [viblo/pymunk#243]
Hi, so I have a question regarding the batch API. Going back to the scenario in my previous git issue, let's say I have on the order of a thousand polygons and I need to apply an impulse (i.e. drag) during each simulation step. Does the new batch API have a nice way of 'batching' these apply impulses? The code below illustrates what I'm currently doing. I'm calling this `apply_drag()` method during each iteration of my main simulation loop which seems to be a little slow... I tried just applying drag every few simulation iterations but the behavior no longer looks realistic. Let me know your thoughts, thank you!
`````python
def apply_drag(polygons, areas):
    for poly, area in zip(polygons, areas):
        poly.body.apply_impulse_at_local_point(
            (
                    DRAG_COEFFICIENT
                    * math.sqrt(area)
                    * poly.body.velocity.length ** 2
                    * -(poly.body.velocity / poly.body.velocity.length)
            ),
        )
        poly.body._set_angular_velocity(
            poly.body.angular_velocity * (1 - ANGULAR_VELOCITY_DECAY)
        )
`````

**Comment by viblo** [comment]
This is an interesting topic! Right now the batch API doesn't support setting anything, only getting. But I do like the idea.

To be most consistent with the current API I could add force and torque as `BodyFields` available, and then add a `update_space_bodies(space, fields, buffers)`  that applies to the specified fields whatever values are in the buffers.

This idea would fix your `set_angular_velocity`, but not `apply_impulse..` Either you could then rewrite the apply impulse method to do the additional calculations done and then set the `velocity` and `angular_velocity` manually, or I should also the apply impulse and apply force options to the batched api as well.

Another thought I have is if this could be solved with a vectories/batch version of `Body.velocity_func` / `Body.update_velocity`? 

By the way, is there some specific reason you call `poly.body._set_angular_velocity(...)` instead of `poly.body.angular_velocity = ...`?

**Comment by rdesc** [comment]
Yes, that addition would be pretty sweet if it provides some speed ups! 

So one thing I did change is I am now getting the velocities batched using the new batch module which seems to be faster than before. The `poly.body._set_angular_velocity(...)` was from a previous version of my code but you're right it's not as readable here haha. And you're right I can update the velocity manually instead of applying an impulse (although I'm surprised that this doesn't really speed things up...). So with these changes I get this:

````python
def apply_drag(polygons, sqrt_areas, velocities):
    for poly, sqrt_area, v in zip(polygons, sqrt_areas, velocities):
        speed = math.sqrt(v[0] ** 2 + v[1] ** 2)
        poly.body.velocity += (
            DRAG_FORCE_CONSTANT
            * sqrt_area  # effective width of the ice floe
            * speed
            * -Vec2d(*v)
            / poly.body.mass
        )

        poly.body.angular_velocity *= (1 - ANGULAR_VELOCITY_DECAY)
```````

**Comment by rdesc** [comment]
I haven't tried modifiying `Body.update_velocity` but when I tried integrating the code above into the callback `Body.velocity_func`, it was signifcantly slower which seems to often be the case with the callbacks

**Comment by viblo** [comment]
Yes, without any batching I would expect the callback functions (like velocity_func), to be the slowest option. Im also not really sure how a nice batched version of this would look like to give actual benefits. (I have also had some thoughts about if this could be optimized within Chipmunk by working on arrays instead of one by one which is sort of related, I dont want to let Pymunk follow a different api that has to be converted)

**Comment by viblo** [comment]
I have just committed a first version of a batched api for setting body properties. 
I also updated the planet example to allow toggling batch api for drawing and updating. https://github.com/viblo/pymunk/blob/master/pymunk/examples/planet.py

Would be great if you could take a look.

**Comment by rdesc** [comment]
I just had a look. This looks great! This addition would let me remove the slow for-loop in my original code for setting the velocity and angular velocity of all the bodies. Did you get a noticeable speed up?

**Comment by rdesc** [comment]
Feel free to close the issue :)

**Comment by viblo** [comment]
In the planets example its a huge difference. The details matters quite a bit, but felt like 2x the fps or something. 
I will do some additional benchmarks like I have for the batch api for getting values to have a more precise measurement and a feel for the overhead produced. Then my plan is to make a release (which will then become 6.7.0) of Pymunk.

**Comment by rdesc** [comment]
I just made the changes on my side with the updated batch module code and I can confirm I also get a > 2x speedup of fps. Thank you!

As reference here's what my updated code looks like.

```python
def batched_apply_drag(sqrt_areas, masses, velocities, angular_velocities, dt, update_buffer):
    speeds = np.linalg.norm(velocities, axis=1)

    new_velocities = velocities + dt * (
        DRAG_FORCE_CONSTANT
        * sqrt_areas[:, None]
        * speeds[:, None]
        * -velocities
    ) / masses[:, None]

    new_angular_velocities = angular_velocities * (1 - ANGULAR_VELOCITY_DECAY)

    v_arr = np.ravel(np.c_[new_velocities, new_angular_velocities]])

    update_buffer.set_float_buf(v_arr.tobytes())
````
