### ISSUE TITLE
lack of a method to create an aproximated disk (polygon)

### ISSUE THREAD

**Issue by bimoware** [viblo/pymunk#248]
Since I couldn't find a way (days ago) to create a disk in python, I decided to use trigonometry functions to dynamically generate my own segments to shape a disk, I'm sharing the code here:
```py
def add_disk():
    arcObj = pymunk.Body(0,0,pymunk.Body.STATIC)
    arcObj.position = (0,0)
    
    arc_coor = []
    for i in range(0,NGON):
        arc_coor.append((
            SIZE[0]/2 + CIRCLE_RADIUS*cos(2*pi *(i/NGON)),
            SIZE[1]/2 + CIRCLE_RADIUS*sin(2*pi * (i/NGON))
        ))

    for i in range(len(arc_coor)):
        if i > 10 and i < 12 : continue
        line = pymunk.Segment(arcObj,
            arc_coor[i], # PB
            arc_coor[0 if (i == (len(arc_coor)-1)) else (i+1)],
            3)
        line.elasticity = 1
        lines.append(line)
    space.add(arcObj,*lines)
```
And, since I use pygame, i render these like so:
```js
for i in range(len(lines)):
    pygame.draw.line(
        screen,
        "white",
        lines[i].a,
        lines[i].b,
        int(lines[i].radius)
    )
```
This works *fine*:
![image](https://github.com/viblo/pymunk/assets/71925280/ac2792f0-c957-4b0f-b4e4-48e236a7f916)
I'm even able to make holes where I want

But my question is, **Is there already a way to do this on pymunk so I don't have this gigantic monstrosity on the middle of my program?**
Because I've searched the docs and I couldn't find anything, google search in general with the "reddit keyword" or not doesn't seem to help either

*If not than it would be really nice to have something similar as a method to create a circle-like shape with the number of polygons as an argument. Something like `pymunk.Disk(body, center, radius, thickness)` with the possibility of adding holes somehow maybe with a parameters that accepts function that will be used as a filter?*

**Comment by viblo** [comment]
Correct, there's no built in shape for this kind of shape. I think your method is fine actually :) 

Im a little hesitant to add too specialized helper-methods to make shapes, since it can easily become many to cover everything that might be of interest..

That said, for your case I wonder if some kind of [CSG ](https://en.wikipedia.org/wiki/Constructive_solid_geometry) type of way of building up the shapes would work. In your case it would be one big circle, with a smaller one inside that make it hollow, and a third to make the opening. On the other hand, this is just on top of my head, so Im not at all sure it make sense from a usage (or implementation) point of view.

**Comment by bimoware** [comment]
Oh I didn't know about this csg concept, thanks.
Looking up hallow circle and such in the docs & google, I unfortunatly couldn't find anything useful;
Nothing mentionned in the docs:
![image](https://github.com/viblo/pymunk/assets/71925280/5f17ec15-491b-4110-bb44-c5533913c0f5)
And only this answer on a [stackoverflow post](https://stackoverflow.com/questions/77737441/how-do-i-make-a-hollow-shape-in-pymunk) stating it's impossible:
![image](https://github.com/viblo/pymunk/assets/71925280/b13c09e5-482f-4ee9-9156-0a1cacd548b3)

😞

**Comment by viblo** [comment]
Ah, maybe I wasnt clear. I meant that if this kind of thing would be added to Pymunk, then maybe a CSG-like approach could work. On the other hand maybe this would come at a performance cost, so that the approximation by segments is better anyway.. 

Right now there's nothing like this in Pymunk, instead you have to do it like you already did, with multiple segments (or multiple polygons depending on the exact case).

**Comment by aatle** [comment]
Looks interesting, I revised the code for future reference:
```python
from math import cos, sin, tau

sides = 24
position = 100, 100
radius = 80
thickness = 3
exclude = 11, 12, 15

body = pymunk.Body(body_type=pymunk.Body.STATIC)
points = [
    (position[0] + radius*cos(tau*i/sides), position[1] + radius*sin(tau*i/sides))
    for i in range(sides)
]
lines = [
    pymunk.Segment(body, points[i], points[(i+1) % sides], thickness/2)
    for i in range(sides) if i not in exclude
]
for line in lines:
    line.elasticity = 1

space.add(body, *lines)
```
It's not that much code so it's best to just copy and paste into one's program, perhaps as a function.

A bunch of segments is how I usually see hollow circles being created in physics engines.

**Comment by bimoware** [comment]
> It's not that much code so it's best to just copy and paste into one's program, perhaps as a function.

Perfect. happy to see a super cool python wrapper in such good care. Amazing response time!
Hope beginners who aren't familiar with cos & sin find this.
